[[redirects]]
  from = "/council-president"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/our-history"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/project"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/events"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/donate"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact-us"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/managehome"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/managepresidents"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/managecourses"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manageprojects"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manageevents"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manageGallery"
  to = "/index.html"
  status = 200

 [[redirects]]
  from = "/download"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/blogs"
  to = "/index.html"
  status = 200 

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
