[[redirects]]
  from = "/en-us/council-president"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/our-history"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/project"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/events"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/gallery"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/donate"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/contact-us"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/blogs"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/board"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/members"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/our-courses"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/Blearnmore/:id"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/Plearnmore/:id"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/Clearnmore/:id"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/Pjlearnmore/:id"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/Bmlearnmore/:id"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/templates"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/download"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en-us/stkpush/promptsent"
  to = "/index.html"
  status = 200


[[redirects]]
  from = "/en-us/join-us"
  to = "/index.html"
  status = 200


[[redirects]]
  from = "/managehome"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/managepresidents"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/managecourses"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manageprojects"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manageevents"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manageGallery"
  to = "/index.html"
  status = 200

 [[redirects]]
  from = "/download"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/blogs"
  to = "/index.html"
  status = 200 

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200
